### ISSUE TITLE
Cloud-Proxy for port scanning

### ISSUE THREAD

**Issue by freb** [tomsteele/cloud-proxy#4]
First, thanks for all the great projects!

I was testing a target network today that has pretty serious rate limiting with a lockout so I thought it would be a good time to try out this project. Going into it, I thought proxychains would allow me to scan the targets, spreading my traffic across the source addresses as long as the nmap scan didn't use raw sockets (i.e. use -sT option or use a non-root user). It did work, but It appears as though proxychains blocks on connect attempts until the connection is fully established with the final destination or until the connection times out per its configuration.

I guess I am just looking for a sanity check on this conclusion. I used both proxychains-ng and proxychains4 and it seemed to work the same. If this is the case, I guess this approach to port scanning is really only for stealth and not for rate limit evasion. Can you confirm this?

**Comment by tomsteele** [comment]
Thanks @freb  :) We're not really going for rate-limiting evasion, though, I think in certain situations that could work. Just depends on the tools we have I guess. I didn't know about this behavior regarding proxychains. Do you have any documentation?

**Comment by freb** [comment]
I didn't find anything official discussing this. But the progress of the scan and the nmap and proxychains messages lead me to this conclusion:

```
[proxychains] Random chain  ...  127.0.0.1:55594  ...  xxx.yyy.z.135:199 <--socket error or timeout!
[proxychains] Random chain  ...  127.0.0.1:55582  ...  xxx.yyy.z.134:199 <--socket error or timeout!
adjust_timeouts2: packet supposedly had rtt of 15013575 microseconds.  Ignoring time.
[proxychains] Random chain  ...  127.0.0.1:55566  ...  xxx.yyy.z.137:199 <--socket error or timeout!
adjust_timeouts2: packet supposedly had rtt of 15013807 microseconds.  Ignoring time.
[proxychains] Random chain  ...  127.0.0.1:55582  ...  xxx.yyy.z.136:199 <--socket error or timeout!
adjust_timeouts2: packet supposedly had rtt of 15012280 microseconds.  Ignoring time.
[proxychains] Random chain  ...  127.0.0.1:55599  ...  xxx.yyy.z.135:139 <--socket error or timeout!
adjust_timeouts2: packet supposedly had rtt of 15013243 microseconds.  Ignoring time.
adjust_timeouts2: packet supposedly had rtt of 15013243 microseconds.  Ignoring time.
[proxychains] Random chain  ...  127.0.0.1:55593  ...  xxx.yyy.z.134:139 <--socket error or timeout!
adjust_timeouts2: packet supposedly had rtt of 15013754 microseconds.  Ignoring time.
adjust_timeouts2: packet supposedly had rtt of 15013754 microseconds.  Ignoring time.
[proxychains] Random chain  ...  127.0.0.1:55599  ...  xxx.yyy.z.137:139 <--socket error or timeout!
```

After some more digging, I did finally find one reference to it here: https://www.bamsoftware.com/wiki/Nmap/ProxyScan

This is the first time I've needed this type of functionality for basic port scanning, so I'm not sure how common it is. I mainly wanted to make sure I wasn't missing anything glaring.

**Comment by tomsteele** [comment]
Interesting, very good to know @freb :)

**Comment by freb** [comment]
@tomsteele, the pentest I was working on last year that prompted this issue came back around. I ended up forking cloud-proxy and adjusting it to work with generic shell commands, including some specific functionality for getting nmap scans split between cloud instances. Not sure if you ever have a need for slowing scan rates way down to evade blacklisting. Either way, here's a link:

<https://github.com/aerissecure/cloud-cmd>

Thanks a bunch for the great work!
